text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir:      output
index_filenames: [ 'index.html' ]
enable_output_diff: true

data_sources:
  - type:       filesystem_unified
    items_root: /
  - type:       changelog
    items_root: /changelog/

watcher:
  dirs_to_watch:  [ 'content', 'layouts', 'lib' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true

prune:
  auto_prune: false
  exclude: [ '.git' ]

google_analytics:
  site_id: UA-719239-21

clicky:
  site_id: 66493146
